### ISSUE TITLE
could you please help me understand how to setup the json file?

### ISSUE THREAD

**Issue by james28909** [cmbarba/pbdns-updater#1]
i have a domain i purchased from porkbun, ive put my qpi and secret key and domain that ends in .pro. i do not have a sub domain so in the json file ive just deleted the input from the subdomain key. the subdomain key is still there but it is empty.

when i run the script i get this:
```

./porkbun-dns-updater ./api_key_file.json
[PBDU "redacted-domain.pro"] Retrieving IP addresses...
[PBDU "redacted-domain.pro"] ERROR: There was a problem retrieving the Porkbun A record. Stopping...
```

and i am not sure what to do next. is there any way you could point me in the right direction? thanks in advance

**Comment by cmbarba** [comment]
You're getting that error because either there's a problem with your json or you don't have an A record already set up in Porkbun. The script only edits existing records, it doesn't create them. Do you already have an A record set up?
